name: Emergency-SOS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # This adds the "Run workflow" button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a quick test
        run: echo "The workflow is now working!"
